version: 2

template: &template
  schedule:
    interval: "monthly"
  commit-message:
    prefix: "fix: "
    prefix-development: "fix(ci): "
  reviewers:
    - superflyxxi

updates:
  - package-ecosystem: "composer"
    <<: *template
    directory: "/"
  - package-ecosystem: "docker"
    <<: *template
    directory: "/"
