version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix"
      prefix-development: "ci"
      include: "scope"
    reviewers:
      - superflyxxi
    assignees:
      - superflyxxi
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix"
      prefix-development: "ci"
      include: "scope"
    reviewers:
      - superflyxxi
    assignees:
      - superflyxxi
  - package-ecosystem: "docker"
    directory: "/tests/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "ci"
      prefix-development: "ci"
      include: "scope"
    reviewers:
      - superflyxxi
    assignees:
      - superflyxxi
