#!/usr/bin/php
<?php
include_once "convert/ConvertFile.php";

function error_handler(int $errno, string $errstr, $errfile = NULL, $errline = 0, $errcontext = NULL)
{
    print_r("Error encountered! ");
    print_r($errstr);
    print_r(" at file ");
    print_r($errfile);
    print_r(":");
    print_r($errline);
    print_r("\n");
    print_r($errcontext);
    ob_flush();
    flush();
    exit($errno);
}
set_error_handler('error_handler');

if (NULL == getEnv("TITLE")) {
    Logger::error("TITLE env variable missing");
    exit(1);
}

$envInput = getEnv("INPUT");
$csvRequest = NULL;
if (substr($envInput, -4 ) === ".csv") {
  $csvRequest = new CSVRequest("/data/".$envInput);
} else {
  if (NULL == $envInput) {
    $arrFiles = array_diff(scandir("/data/"), array(
        '..',
        '.'
    ));
  } else {
    $arrFiles[] = $envInput;
  }
  //$csvFilename = getEnvWithDefault("TMP_DIR", "/tmp")."/tmp.csv"; 
  //$csvFile = new SplFileObject($csvFilename, "w");
  $csvFile = new SplTempFileObject();
  $csvFile->fputcsv(array("filename"));
  foreach ($arrFiles as $infile) {
    $csvFile->fputcsv(array($infile));
  }
  $csvRequest = new CSVRequest($csvFile->getRealPath());
}

exit($csvRequest->convert());
?>
