name: Cleanup Docker Registries

on: [delete]

jobs:
  remove_ghcr_images:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch
        run: echo "BRANCH=$( echo ${{github.event.ref}} | sed 's#/#-#g')" >> $GITHUB_ENV
      - name: Debug Branch
        run: echo ${{env.BRANCH}}
      - name: Remove image from GHCR
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          oganization: superflyxxi
          container: video-converter
          token: ${{ secrets.GHCR_TOKEN }}
          tag-regex: ${{env.BRANCH}}
          dry-run: true
      - name: Remove test image from GHCR
        uses: bots-house/ghcr-delete-image-action@v1.0.1
        with:
          owner: superflyxxi
          name: video-converter
          token: ${{ secrets.GHCR_TOKEN }}
          tag: test-${{env.BRANCH}}
