name: Cleanup Docker Registries

on: [delete]

jobs:
  remove_ghcr_images:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch
        run: echo "BRANCH=$( echo ${{github.event.ref}} | sed 's#/#-#g')" >> $GITHUB_ENV
      - name: Debug Branch
        run: echo ${{env.BRANCH}}
      - name: Remove image from GHCR
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          organization: superflyxxi
          container: video-converter
          token: ${{ secrets.GHCR_TOKEN }}
          tag-regex: "^${{env.BRANCH}}$"
          dry-run: false
      - name: Remove image from GHCR
        uses: vlaurin/action-ghcr-prune@v0.3.0
        with:
          organization: superflyxxi
          container: video-converter
          token: ${{ secrets.GHCR_TOKEN }}
          tag-regex: "^test-${{env.BRANCH}}$"
          dry-run: false
